# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                peer
local   all             all                                     trust
host    all             all             0.0.0.0/0               md5
# Allow replication connections from replica
host    replication     replicator      0.0.0.0/0               trust
