# Minimal postgresql.conf for primary with WAL settings for streaming replication
listen_addresses = '*'
port = 5432
max_wal_senders = 5
wal_level = replica
archive_mode = off
hot_standby = on
wal_keep_size = 64
# point to the mounted pg_hba.conf
hba_file = '/etc/postgresql/pg_hba.conf'
logging_collector = on
log_directory = 'pg_log'
log_filename = 'postgresql-%a.log'
